### PR TITLE
Styled the dropdown

### LINKED ISSUE #3319: dropdown too small + inconsistent styling
- dropdown is too small for mobile
- there needs to be more spacing between elements
- item text is wrapping into checkboxes
- equal spacing (8px) around elements in search component (right now it's too tall, the curser is on the left border, search icon is too far from right border)
- if possible, open list in full, or at least until the bottom of the screen

(click to zoom)

Frame 1451

### PR DESCRIPTION
**Pull request by grafitto**
fixes #3319 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [x] Test for side effects
- [x] UI responsiveness
- [x] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Review by fnocetti — CHANGES_REQUESTED** [review]
@grafitto very nice job!
I'm attaching a screenshot of how it looks for iPhone 5. At that resolution at least one of the options is hidden at the bottom of the screen. Can you take a look? Maybe we can use another breakpoint or just reduce a bit the max height.

Thank you!
Screen Shot 2020-11-25 at 10 40 11 AM

**Comment by fnocetti** [comment]
@grafitto thanks for taking a look! I think that the new height limit is still not enough. I did some quick tests and I think a max-height for the rw-list should be around 340 pixels. But that's my opinion.

@simonfossom could you please let us know what are the minimal screen resolutions we usually consider for the CSS?

**Comment by simonfossom** [comment]
> @grafitto thanks for taking a look! I think that the new height limit is still not enough. I did some quick tests and I think a max-height for the rw-list should be around 340 pixels. But that's my opinion.
> 
> @simonfossom could you please let us know what are the minimal screen resolutions we usually consider for the CSS?

The minimum that we cater to is 320px.

**Comment by grafitto** [comment]
> > @grafitto thanks for taking a look! I think that the new height limit is still not enough. I did some quick tests and I think a max-height for the rw-list should be around 340 pixels. But that's my opinion.
> > @simonfossom could you please let us know what are the minimal screen resolutions we usually consider for the CSS?
> 
> The minimum that we cater to is 320px.

I have changed max height to 340px

**Comment by fnocetti** [comment]
LGTM!

**Pull request merged**
