### PR TITLE
Sort items in multiselect filters when expanded

### LINKED ISSUE #2447: Keep alphabetical ordering in filters for relationship-based options when expanded
We introduced custom ordering for thesauris and filters.

Still, for the alphabetical ordering of filters based on relationships, those still need to default to alphabetical when the filter options are expanded (The collapsed version still should show based on occurrence of the values)

### PR DESCRIPTION
**Pull request by habbes**
fixes #2447

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by habbes** [comment]
After a while, I realized that I had done something similar in the past, and just needed to a `sort` prop to the relevant `Multiselect` component.

**Comment by txau** [comment]
@habbes just in case, in the past I remember you fixed removing the alphabetical sorting so people could sort arbitrarily from the thesauri configuration. The problem is that relation based filters, do not have a way of sorting.

So, this should keep arbitrary sorting for thesaurus based, and alphabetical for relationship based.

Please, consider that as part of the QA.

**Comment by habbes** [comment]
@txau thanks. Let me cross-check to ensure thesauri filters still work as expected

**Comment by habbes** [comment]
@txau my earlier commit also affected thesauri filters, but I've fixed that, only relationship filters are sorted now.

**Comment by txau** [comment]
@habbes ok. I hope @RafaPolit can QA this.

**Comment by daneryl** [comment]
@habbes LGTM, pls rebase.

**Pull request merged**
