### PR TITLE
triming property labels before been used as names

### PR DESCRIPTION
**Pull request by konzz**
Fixes issue #1633 

PR checklist:
- [x] End-to-end test
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by txau** [comment]
Make sure the trailing space is removed from the front-end as well.

**Comment by txau** [comment]
Its still saving the trailing space:

1. Create a template
2. Add a filed
3. Add an ending space to the field title
4. Save
5. Edit that same template
6. The field name still has an space at the end

**Comment by konzz** [comment]
@txau Don't think that was the problem, but ok I can remove it.

**Comment by txau** [comment]
@konzz ok. This is actually pretty simple, just remove trailing spaces from both labels and property names.

**Comment by txau** [comment]
I'm still getting a trailing space in the label?

**Comment by txau** [comment]
Still happening?

**Comment by txau** [comment]
LGTM

**Pull request merged**
