### PR TITLE
1127 improving installation instructions

### PR DESCRIPTION
**Pull request by habbes**
Fixes issue #1127 

PR check list:

- [ ] Client test
- [ ] Server test
- [ ] End-to-end test
- [ ] Pass code linter to client and server
- [ ] Update READ.me ?

QA check list:

- [ ] Smoke test the functionality described in the issue
- [ ] Smoke test potential collaterals
- [ ] UI responsiveness
- [ ] Tested in a browser other than chrome
- [ ] Code review ?

NOTE: Make sure the build passes.

### CODE REVIEW

**Comment by habbes** [comment]
I've added some steps to the instructions (such as `git clone`) and also corrected issues in other steps.

**Comment by habbes** [comment]
The instructions still feel a bit mechanical, I think I can make it a bit friendlier and accessible to users not familiar with the tech stack with a bit more prose. If you agree, please don't merge this PR yet.

**Comment by habbes** [comment]
I've updated the README, modified the structure a bit, added a TOC and a few additions to the steps.

**Comment by RafaPolit** [comment]
The current node installation instructions would install Node v4.x instead of 6.x as required.

**Comment by habbes** [comment]
Thanks @RafaPolit, let me make corrections.

**Comment by habbes** [comment]
@RafaPolit regarding the node version, I had copied from the older README, if I update the the link `https://deb.nodesource.com/setup_6.x` I assume it'll downloaded the latest 6.x (which is 6.11.x I think). I had some errors when working with 6.11.1 with Uwazi and had to downgrade to 6.9.5 (I use `nvm`).

**Pull request closed without merging**
