### PR TITLE
Scroll to text reference when document opened in relationships view

### LINKED ISSUE #2237: "view" should take one to the referenced paragraph, not just the document
Here is a reference I created:
Screenshot_2019-03-14 Free • FPIC
When I click "view", I would expect to be taken to the referenced paragraph, but what I end up is this:
Screenshot_2019-03-14 PROTOCOLO CP Y CPLI DEL PUEBLO NASA CERRO TIJERAS • Page 1 • FPIC
So, that's the beginning of the document, not the referenced paragraph. That's quite impractical.

### PR DESCRIPTION
**Pull request by habbes**
fixes #2237 and #687

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by habbes** [comment]
Instead of using a timeout delay to scroll the document to the location in the document containing the text reference, I added a `documentLoaded` event when the document is ready in the document viewer. When clicking the "View" button in the text reference from another document, the target document will be loaded, and the `documentLoaded` event is used to know when to start scrolling.

**Comment by daneryl** [comment]
@habbes working good, what do you think it will take to change this to a url state instead of a redux state ? this way we do not need the events, simpler code in theory, and text references can be linked and shared, @txau @RafaPolit

**Comment by RafaPolit** [comment]
We are going to implement links for the text relationships, so it is shareable with others.

**Comment by habbes** [comment]
@joan @RafaPolit I've refactored the feature to use url parameters that contain information necessary to scroll to the text reference. It's ready for QA.

**Comment by daneryl** [comment]
@habbes, @RafaPolit i thinks we should use only reference id as a url parameter, is there a reason to use multiple parameters on the url to do this ?

**Comment by habbes** [comment]
@daneryl the function that does the scrolling uses the range start to decided which page to scroll to. I don't know if there reference is in the store when the page is loaded, in that case maybe we could just use the id to look for the correct reference in the store to get the additional properties.

**Comment by daneryl** [comment]
@habbes take a look and check if you can do it that way pls.

**Comment by habbes** [comment]
@daneryl, I've pushed an update. Now you only need to pass the reference id in the url (using the `ref` query parameter).

**Pull request merged**
