### PR TITLE
when importing a zip, csv should be import.csv

### LINKED ISSUE #2310: Import CSV 2.0
- [x] Add an icon in uploads for importing CSV file
- [x] Halt on first error and provides feedback
- [x] Add support for multiple languages (add id and lang columns)
- [x] Support updates when Uwazi ids are provided
- [x] Support file uploads (upload a zip)
- [ ] validate zip has only one csv
- [x] When I don't have a lang, I use the default lang to create the records
- [ ] ~~Add an icon for importing thesauri in a thesauri~~

### PR DESCRIPTION
**Pull request by daneryl**
fixes #2310 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by habbes** [comment]
@daneryl I've tested again and now it seems to work fine.

I found the icon used for the error message to be strange, but I don't think that's a major issue
Screenshot 2019-07-19 at 15 31 12

I also tried using a file named `import.csv` that was actually an image and not an a csv file and it showed the following error:
Screenshot 2019-07-19 at 15 34 53

I guess that's okay as well.

And finally, I created a template with a required field and used imported a csv file that does not have  that field. The import worked without reporting any issues. And the entities were create successfully, without the required field. Of course I don't think this is an issue with the import feature, I just think it means we don't have server-side validation of entities against the template schema.

If the error icon and the handling of non-csv file are note considerable issues, then this feature looks good to me.

**Comment by daneryl** [comment]
@habbes, thanks, there is an issue to work on the ui for the import csv #2353, maybe we should include the icon that you mention, anyways that a generic, the only thing i wanted to fix here is the no handling errors situation. specific entities validation etc its a whole other topic.

**Comment by habbes** [comment]
@daneryl then in that it's good enough for me.

**Comment by daneryl** [comment]
@habbes, @RafaPolit, @txau  maybe a small validation to check if the csv its actually a csv ? but dont know if we can do that properly

**Pull request merged**
