### PR TITLE
Do not select empty thesauri group by default

### LINKED ISSUE #2072: When thesauri groups are empty they always appear as selected
When editing an entity with a multi-select populated by a thesauri. It has no impact on the data consistency or filtering, but its confusing for users.

screenshot from 2018-11-08 14-34-37

### PR DESCRIPTION
**Pull request by habbes**
fixes #2072

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by daneryl** [comment]
@habbes @txau working ok, should we not show the option at all if there is nothing to select there ?

**Comment by RafaPolit** [comment]
@habbes and I have discussed a little bit about this, and he is changing for the option proposed by @daneryl of hiding the value if no child items exist.

**Comment by habbes** [comment]
@RafaPolit @daneryl I've updated the code, now empty groups are not rendered when editing MultiSelect fields.

**Comment by daneryl** [comment]
@habbes LGTM, rebase and will merge.

**Comment by habbes** [comment]
@daneryl rebased

**Pull request merged**
