### PR TITLE
update dependencies and fix css route

### PR DESCRIPTION
**Pull request by darwinsalinas**
fixes #
With the original dependencies not working on macos catalina

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by RafaPolit** [comment]
Thanks for the PR.

As you can see by the failing tests, this update broke most of the Component snapshots that included the `<React.Fragment>` approach to including multiple 'first class citizens' of a group by nesting them under the React.Fragment tag.

The resulting snapshots apparently disregard the React.Fragment altogether, which could be expected, but the snapshots need to be updated nonetheless in order for the PR to be able to merge.

Did you run the unit tests locally?

Thanks again.

**Comment by RafaPolit** [comment]
Also, inspecting the changes, you have updated only two packages, yet there are 8000 changes in the yarn.lock file.  Did you delete it and re-generated it from zero? Or were those changes just due to updating those two libraries?

**Comment by darwinsalinas** [comment]
Yes, I regenerated the file because Yarn always installed the same previous versiones.

The tests were already failing since before making changes to dependency versions

**Comment by darwinsalinas** [comment]
I am runnign my develpment environment in macos Catalina with Node 10.x.x

**Comment by RafaPolit** [comment]
I believe this has been addressed in recent pull requests without the need to recreate the entire yarn.lock file.

I'll confirm with the team that in fact macOS Catalina is working (@fnocetti ?) with Node 10.x.x.

If it is, there is no further need to merge this.  Thanks.

**Pull request closed without merging**
