### PR TITLE
2425 thesauri import ui

### LINKED ISSUE #2425: Implement UI for importing CSV Thesauri (and MicroThesauri)
Allow importing values from Settings -> Thesauri

Our first hunch is to do this as follows:
- Go into settings, thesauri
- Select to edit an existing thesauri or create a new one
- Assign a name to the thesauri (if it hasn't got one) - we could infer the name from the file name when selecting the file, but this is pushing it)
- Save

What do you think @txau

### PR DESCRIPTION
**Pull request by habbes**
fixes #2425

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by habbes** [comment]
This feature allows you to import a CSV file into an existing thesaurus, as well as import a CSV file while creating a new thesaurus.

This is achieved by saving the thesaurus form data before running the import.

This is all handled server-side and reuses the `POST /api/thesauris` endpoint (based on feedback from @joan).

Ready for PR

**Comment by daneryl** [comment]
@habbes when an error occurs on the server, i can not try to upload again, can you take a look what is happening ? apart from that looks good !

**Comment by Joan** [comment]
(👋 @habbes – it's fun to regularly follow the progress of this project because of these mistake mentions, but yeah, just in case: wrong @Joan 😇)

**Comment by habbes** [comment]
> (👋 @habbes – it's fun to regularly follow the progress of this project because of these mistake mentions, but yeah, just in case: wrong @Joan 😇)

Hey @Joan, sorry for the mistaken mentions, I had not noticed it until now 😄

**Comment by Joan** [comment]
No worries at all, good luck with the project 😊

**Comment by habbes** [comment]
@daneryl could you specify how to reproduce the server error that prevented you from importing data?

I've fixed the failing e2e tests as well as added validation to prevent blank names on thesauri.

**Comment by daneryl** [comment]
> @daneryl could you specify how to reproduce the server error that prevented you from importing data?

@habbes yes if a validation error occurs on the server like duplicated name you will get a popup saying "validation failed" or something like that, after that point i was not able to upload a new file to re import.

**Comment by habbes** [comment]
@daneryl after getting an error like "validation error", I'm still able to upload a file again.

**Comment by daneryl** [comment]
@habbes, ok ill check again then and merge if everything ok

**Comment by daneryl** [comment]
@habbes still happening to me, try this, 

- new thesauri
- leave title blank
- import a file (you will get a validation error)
- write some title
- import a file
- the file it is not uploaded

**Comment by habbes** [comment]
It appears the Chrome does not fire the `onchange` event if you select the same file the second time. I tried to use the `oninput` event instead, but the behaviour is still the same. I'll try some of the workarounds proposed here: https://stackoverflow.com/questions/6623310/input-file-onchange-event-not-being-fired-in-chrome

**Comment by habbes** [comment]
@joan I've fixed the issue, it should not work on both Chrome and Firefox.

**Pull request merged**
