### PR TITLE
1614 map improvements

### PR DESCRIPTION
**Pull request by konzz**
Fixes issue #1614 #1612 

PR checklist:
- [x] End-to-end test
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by txau** [comment]
Some tweaks:
1. Fix the CSS styles for lat-long boxes in the side panel edit view.
2. In side panel edit view, when the cursor is over the marker shows a pointing finger and when its out shows a dragging hand. Make the cursor a pointing finger when its out for the marker area so that users know they can place a pinpoint. Make the cursor a dragging hand when its over the marker.
3. There is JS error:

screenshot from 2018-05-18 20-02-36

**Comment by txau** [comment]
Some improvements to the edit view in entities:
1. Remove the ":" for lat/long labels.
2. Leave some horizontal space between the lat/long labels and the input boxes (around 5px?)
3. Increase the map height by 50%.

screenshot from 2018-05-21 08-08-02

**Comment by txau** [comment]
1. Still need some CSS fixing in the side panel in edit mode:

screenshot from 2018-05-23 07-59-07

- Leave some vertical space between fields.
- On the left side, they should be aligned with the map.
- On the right side, it should end with the regular margin.

2. I've noticed some annoying behavior with the pinpointing. If the click event its too long, it does not work. This sometimes gives the feeling of the features just not working.

The rest of the problems have been fixed.

**Comment by txau** [comment]
There is a weird horizontal scroll and a margin:

screenshot from 2018-05-23 09-33-09

**Comment by konzz** [comment]
@txau please report the browser you are using since I don't see the fields the same way as you do.

**Comment by txau** [comment]
@konzz Chromium Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by txau** [comment]
@konzz margins are related to a CSS conflict between list view and map view. I think its better if @danicatalan fixes it.

This PR LGTM.

**Pull request merged**
