### PR TITLE
Showing a permanent notification when the connection with

### PR DESCRIPTION
**Pull request by konzz**
Fixes issue #2183 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by daneryl** [comment]
@konzz resolve conflict and tests of socket.js ?

**Comment by konzz** [comment]
@daneryl I just pcreated this so @RafaPolit  pickups the work I was doing, not sure how is he going with this

**Comment by daneryl** [comment]
ah, ok

**Comment by konzz** [comment]
anyway I'm gonna close this, since I suppose @RafaPolit will do his own PR

**Comment by txau** [comment]
@konzz the message appears for a few seconds in some situations where is not as desirable:
- When logging in or out
- When switching languages

**Pull request merged**
