### PR TITLE
cookie popup

### LINKED ISSUE #2372: We use cookies notification popup
Create a popup that displays a message about the use of cookies in Uwazi

### PR DESCRIPTION
**Pull request by konzz**
fixes #2372 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by konzz** [comment]
CollectionSettings Form was on very low coverage, was using a normal form, with onChange methods for each property tracking it in the state, its been refactored to use LocalForm. It will probably require an extended QA just to make sure that everything is working.

**Comment by daneryl** [comment]
@konz im not able to save the cookie policy option on the collection form.

also the form throw this:
Screenshot 2019-06-20 at 10 50 17

when i try to save custom page:
Screenshot 2019-06-20 at 10 53 15

**Comment by RafaPolit** [comment]
For me, all looks good, except for the actual notification:

It renders a green check that reads the notification.  It is BY NO MEANS clear that I have to actually click on that to accept / close it.  I think this is as much an MVP as it can, and I am inclined to merge it, but still it may be actually more confusing than useful.

@txau ?
Screenshot from 2019-06-24 15-13-30

**Comment by RafaPolit** [comment]
I was able to 'inline translate' the text within the notification, but the System translation for this (and another key) appears blank:

Screenshot from 2019-06-24 15-25-29

**Pull request merged**
