### PR TITLE
Updated huridocs logo on the footer

### LINKED ISSUE #3711: Outdated Uwazi footer needs update (2 pts)
The hover text on the Uwazi logo in the footer still shows the old HURIDOCS logo. It should be updated to show the redesigned logo we debuted in December. 

It also lists countries where we no longer have developers located (Germany, USA) and lacks countries where we do (Argentina, Uruguay, the Netherlands...). Maybe to avoid constant updates to this text as our team grows and changes, it'd be easier to simply say "Uwazi is developed by [HURIDOCS logo]" or "Uwazi is developed by [HURIDOCS logo] team members located all over the world." ?

Additionally, the alt-text doesn't capitalize Uwazi's name correctly: it’s all lowercase when it should be properly capitalized (Uwazi, not uwazi). 

alt text footer
Uwazi footer

### PR DESCRIPTION
**Pull request by grafitto**
fixes #3711 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by grafitto** [comment]
Here is how it looks like
image

**Comment by konzz** [comment]
@grafitto check at the last comment from Jaume in the issue, He says to just leave the Uwazi is developed by huridocs part.

**Comment by grafitto** [comment]
Here is how it looks
image

**Comment by txau** [comment]
@grafitto if you take a look to the final code, it reads as "Uwazi us developed by ". And the img has as alt and title "uwazi" instead of Huridocs:

image

Ideally:
- It reads as "Uwazi is developed by Huridocs"
- The logo is a link to huridocs.org
- If we have title and alt, we could go with "Huridocs" for title and "Human Rights Documentation Systems" for alt

**Comment by whyfrycek** [comment]
Thanks for updating this! Please change "Huridocs" to "HURIDOCS", as all caps is the preferred spelling. Thank you!

**Comment by grafitto** [comment]
> Thanks for updating this! Please change "Huridocs" to "HURIDOCS", as all caps is the preferred spelling, and the full name is "Human Rights Information and Documentation Systems". Thank you!

Since this PR is already closed, I will make the changes in a new PR and Issue

**Pull request merged**
