### PR TITLE
Update map tiles url

### PR DESCRIPTION
**Pull request by konzz**
fixes #

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by vasyugan** [comment]
Has something else changed in addition? I applied this patch to my Uwazi 1.5 install and the page still remains blank.

**Comment by konzz** [comment]
No, we changed the URL and the maps started rendering again. Do you have any errors?

**Comment by vasyugan** [comment]
> No, we changed the URL and the maps started rendering again. Do you have any errors?

I don't see any console output, and Uwazi's log directory is empty. So the answer is no. If it helps, I can paste the source code of the page that Uwazi serves into a gist, maybe you can find something suspicious there.

**Comment by konzz** [comment]
Sure, please send it.

**Comment by vasyugan** [comment]
> Sure, please send it.

Great! Here is [the gist](https://gist.github.com/vasyugan/5a6e828e8afc99faafea7b9f20ee585e)

**Comment by vasyugan** [comment]
> @konzz
> 
> > Sure, please send it.
> 
> Great! Here is [the gist](https://gist.github.com/vasyugan/5a6e828e8afc99faafea7b9f20ee585e)

But I guess more important than the HTML source code are the linked scripts

    <script src="/pdfjs-dist.ac4045da05ad672ce8a4.js"></script>
    <script src="/nprogress.e33c269884955d0dfba6.js"></script>
    <script src="/vendor.b8742303196231ba227d.js"></script>
    <script src="/main.3fd7b4085136c68bd751.js"></script>

Not sure which one is responsible for the map though...

**Comment by vasyugan** [comment]
[here](
https://gist.github.com/vasyugan/e8d75f886d1715912610ee3952c1b86d) is the main js script which seems to be the one responsible for getting the tiles

**Pull request merged**
