### PR TITLE
query builder now calculates aggregations for dictionary groups

### PR DESCRIPTION
**Pull request by konzz**
Fixes issue #1712 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by txau** [comment]
Got a JS error while editing the values in for an entity with groups.

screenshot from 2018-07-02 15-12-27

**Comment by txau** [comment]
When editing, groups don't appear with alphabetical order when the options are unfolded:
screenshot from 2018-07-02 15-15-18

Also when editting, when folded, they do not show the selected groups:
screenshot from 2018-07-02 15-16-25

**Comment by txau** [comment]
Apart from these comments, the functionality seems to work, but I rather re-QA it once the bugs are fixed.

**Comment by konzz** [comment]
@txau this ready for QA; but lets have a call

**Pull request merged**
