### PR TITLE
Encapsulate elastic tenants

### LINKED ISSUE #3391: encapsulate tenant into elastic low level api
> search module its being instantiated, only to be able to test it, tests and prod use different variables to determine the tenant, this is confusing and its already producing code that does not send the correct tenant/index on request to elastic. 

#3389

### PR DESCRIPTION
**Pull request by daneryl**
fixes #3391 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Review by fnocetti — COMMENTED** [review]
After doing a code review the changes look good to me. This is a really good and needed improvement, awesome!
Now I'll proceed to do a smoke testing.

**Comment by fnocetti** [comment]
I did a quick smoke testing and it looks good.
I'm getting this TS errors when running the application:

```
app/api/search/specs/search.searchGeolocations.spec.ts:25:24 - error TS7006: Parameter 'results' implicitly has an 'any' type.

25   const cleanResults = results =>
                          ~~~~~~~

app/api/search/specs/search.searchGeolocations.spec.ts:26:26 - error TS7006: Parameter '_memo' implicitly has an 'any' type.

26     results.rows.reduce((_memo, row) => {
                            ~~~~~

app/api/search/specs/search.searchGeolocations.spec.ts:26:33 - error TS7006: Parameter 'row' implicitly has an 'any' type.

26     results.rows.reduce((_memo, row) => {
                                   ~~~

app/api/search/specs/search.searchGeolocations.spec.ts:54:33 - error TS7006: Parameter 'e' implicitly has an 'any' type.

54     const entity = cleaned.find(e => e.sharedId === 'entity_isLinkedToPrivateEntity');
                                   ~

app/api/search/specs/search.searchGeolocations.spec.ts:62:11 - error TS2531: Object is possibly 'null'.

62     await db.mongodb.collection('templates').drop();
             ~~~~~~~~~~

app/api/search/specs/search.searchGeolocations.spec.ts:63:11 - error TS2531: Object is possibly 'null'.

63     await db.mongodb.collection('templates').insertOne(tplWithoutGeolocation);
             ~~~~~~~~~~
```

@daneryl could you take a look and also fix the conflict?

Thank you!

**Review by fnocetti — CHANGES_REQUESTED** [review]
Please, check previous comment

**Comment by daneryl** [comment]
> I did a quick smoke testing and it looks good.
> I'm getting this TS errors when running the application:
> 
> ```
> app/api/search/specs/search.searchGeolocations.spec.ts:25:24 - error TS7006: Parameter 'results' implicitly has an 'any' type.
> 
> 25   const cleanResults = results =>
>                           ~~~~~~~
> 
> app/api/search/specs/search.searchGeolocations.spec.ts:26:26 - error TS7006: Parameter '_memo' implicitly has an 'any' type.
> 
> 26     results.rows.reduce((_memo, row) => {
>                             ~~~~~
> 
> app/api/search/specs/search.searchGeolocations.spec.ts:26:33 - error TS7006: Parameter 'row' implicitly has an 'any' type.
> 
> 26     results.rows.reduce((_memo, row) => {
>                                    ~~~
> 
> app/api/search/specs/search.searchGeolocations.spec.ts:54:33 - error TS7006: Parameter 'e' implicitly has an 'any' type.
> 
> 54     const entity = cleaned.find(e => e.sharedId === 'entity_isLinkedToPrivateEntity');
>                                    ~
> 
> app/api/search/specs/search.searchGeolocations.spec.ts:62:11 - error TS2531: Object is possibly 'null'.
> 
> 62     await db.mongodb.collection('templates').drop();
>              ~~~~~~~~~~
> 
> app/api/search/specs/search.searchGeolocations.spec.ts:63:11 - error TS2531: Object is possibly 'null'.
> 
> 63     await db.mongodb.collection('templates').insertOne(tplWithoutGeolocation);
>              ~~~~~~~~~~
> ```
> 
> @daneryl could you take a look and also fix the conflict?
> 
> Thank you!

weird, the errors shown here are based on old code, i just rebased and checked the types, no errors for me, can you check again pls, thanks !

**Review by fnocetti — APPROVED** [review]

**Pull request merged**
