### PR TITLE
Fix video player css

### LINKED ISSUE #2391: Screwed up CSS for videos
Screenshot from 2019-06-18 18-42-31

### PR DESCRIPTION
**Pull request by habbes**
fixes #2391 and #1686

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by habbes** [comment]
I think I've gotten the css to work well for both self-hosted and video/vimeo videos, both in the cards, the sidebar and the entity viewer:

Screenshot 2019-07-19 at 13 46 34
Screenshot 2019-07-19 at 13 46 59

I also tried to make sure it doesn't break the video player inside pages

Screenshot 2019-07-19 at 14 22 52

**Comment by habbes** [comment]
While doing the QA please test with videos with different aspect ratios, different sources (youtube, vimeo, self-hosted, etc.), and also ensure it doesn't break videos in pages.

**Comment by txau** [comment]
@habbes I'll do the QA

**Comment by txau** [comment]
@habbes LGTM. Maybe delete this comment and merge:
```
 /*
    use aspect-ratio box technique to make
    video player scale seamlessly and responsively
    https://css-tricks.com/aspect-ratio-boxes/
  */
```

**Pull request merged**
