### PR TITLE
Template colors

### LINKED ISSUE #2235: Some labels for entity type are not legible: White letters with white background
When creating entity types, uwazi seems to randomly assign background colours to their labels, and one of them is white which ends me up with seemingly empty labels, with white text on whit background
Screenshot_2019-03-14 Library • FPIC

### PR DESCRIPTION
**Pull request by habbes**
fixes #2235 #1338 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by txau** [comment]
@habbes the functionality LGTM. It would be great if @daneryl or @konzz can take a look to the code.

**Comment by habbes** [comment]
I'm working on issue #1338. It overlaps with this PR, if this has not yet been QA'd, then we could keep it open and I can merge what I'm working with this PR.

**Comment by txau** [comment]
@habbes sure. I guess this is not ready for qa yet, no?

**Comment by habbes** [comment]
@txau now it's not ready yet

**Comment by habbes** [comment]
@txau I think I'm almost done with the feature. I'm just missing a few tests. Meanwhile you can check it out and see whether the UX is okay.

**Comment by txau** [comment]
Pretty awesome @habbes. Let's finish the tests and do a code review.

**Comment by habbes** [comment]
This branch is ready for QA

**Comment by txau** [comment]
LGTM

**Comment by daneryl** [comment]
@habbes LGTM, pls solve codeclimate lint errors and rebase

**Comment by habbes** [comment]
@daneryl I've fixed the linter errors regarding non-required props.

However I'm not sure how to fix the code block similarity, it complains that:
```
super(props)
this.state = { .... }
```
is similar in two components

**Comment by daneryl** [comment]
@habbes its ok we do not fix all similar code issues, only the ones we consider make sense.

**Pull request merged**
