### PR TITLE
Made migration script use DB authentication and host if available

### LINKED ISSUE #3365: Migrations (via install.sh) can fail with (apparent) data loss with an authenticated database
If Uwazi is configured with an authenticated database, then if the Uwazi installation is updated using `install.sh`, the migration step fails in a way that can cause data loss. The script outputs the error below, whether or not the DB authentication information has been provided in environment variables. Afterwards, the database and `uploaded_documents` directory both contain the expected file contents, but Uwazi does not list the files.

It's possible there's an easy way to restore the data, but the fundamental problem is that the migration script doesn't check for or use the DB authentication and host information that the main server script does.

A minimal solution should add that functionality to `migrate.ts`. In addition, it would probably be prudent to check for an authenticated database and output more detailed error information and instructions for completeing the migration, and handle the error more gracefully.

The current error output:
```
Updating database schema...
2020-12-14T04:28:31.230Z [localhost] uncaughtException: command find requires authentication
MongoError: command find requires authentication
    at MessageStream.messageHandler (/opt/uwazi/uwazi-production/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:263:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (/opt/uwazi/uwazi-production/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/opt/uwazi/uwazi-production/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at Socket.ondata (_stream_readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:129:14)
Reindexing ElasticSearch...
Deleting index uwazi_development... [done]
Creating index uwazi_development...
 - Base properties mapping
 - Custom templates mapping
2020-12-14T04:28:35.165Z [localhost] Uncaught Reindex error.
command find requires authentication
Will exit with (1)

Restoring index settings... [done]
2020-12-14T04:28:35.374Z [localhost] uncaughtException: command find requires authentication
MongoError: command find requires authentication
    at MessageStream.messageHandler (/opt/uwazi/uwazi-production/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:263:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (/opt/uwazi/uwazi-production/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/opt/uwazi/uwazi-production/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at Socket.ondata (_stream_readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:129:14)
```

### PR DESCRIPTION
**Pull request by duncanka**
Largely fixes #3365 (though more robust error handling and messages would still be a good idea).

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by daneryl** [comment]
@duncanka this looks good.
install.sh also reindex elasticsearch after running the migrate script, the reindex script will also need authorization to connect to mongo if you want to add it for this PR ?

**Comment by duncanka** [comment]
Makes sense. Just added it. Sort of makes me wonder if this functionality should just be dropped directly into the `DB` module, but this should work for now.

**Comment by daneryl** [comment]
@duncanka there is more places where connect is being used on CLI scripts, feel free to add this on to the DB module. if this is enough for you we can keep track of that refactor on another issue and merge this as is.
i have updated uwazi so that it runs github actions on forked pull_requests, there is a couple of lint and ts errors if you can fix them before merge ? thank you for the PR and the feedback.

**Comment by duncanka** [comment]
I think it'd be better to leave making this a shared, more robust part of the `DB` module as another issue.

In fact, I'm not even sure I can fix the type check issues...as you might be able to tell by my force pushes, I have no idea what I'm doing in TypeScript. :sweat_smile: Surely there's a paradigmatic way to only pass the auth info if it's defined? Does the entire `connect` call need to be wrapped in an `if`?

**Comment by daneryl** [comment]
@duncanka for the type error, you need to pass undefined in case there is no auth, you can initialise the var as undefined like this
```let dbAuth;```
the problem then will be that TS will complain because dbAuth has no type, and the dbAuth type is not exported from DB module, i think the best way is to use the mongooseOptions type both in the migration script and the DB module instead of the dbType. 
if you want i can make the changes in another PR, or give me permission to push on you branch.

**Comment by duncanka** [comment]
Yeah, that's exactly the difficulty that I had trying to resolve this. I'm not sure exactly what mongooseOptions type you're referring to, so maybe best if you make the changes yourself. I believe you should already have access to push to the branch—the "allow edits by maintainers" box is checked on GitHub.

**Comment by daneryl** [comment]
@duncanka sorry i meant ConnectionOptions interface from mongoose oficial types, i have made the change, all seems good.
there is a test failing but i do not think this is  because of this changes. we have the same e2e failing on other branches. ill merge this as soon as it gets fixed.

**Pull request merged**
