### PR TITLE
Semantic search

### PR DESCRIPTION
**Pull request by habbes**
Fixes issue #2197 #2355 

This feature is behind a feature toggle, add to the settings 
`"features" : {
        "semanticSearch" : true
    }`
This wont have UI so must be done in the database

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by txau** [comment]
- Order matches with more % on the top
- Be able to close the semantic search panel
- Default minimum relevant sentences -> 1
- Long searches are messing up with the UI
- Change sliders granularity to steps of 1%
- Fix CSS and increase font size for the matches in cards

**Comment by RafaPolit** [comment]
Please: make sure that the low coverage threshold is only commented tests.  If it is not and there is a bunch of areas missing tests, DO NOT merge.

**Comment by RafaPolit** [comment]
Waiting on some final tests before merging. @habbes

**Comment by habbes** [comment]
@RafaPolit I've fixed most of the linter issues, the remaining ones are mostly about props destructuring. I've also added a couple of tests to `DocumentResultsPanel` and `NumericRangeSlide`, though their ratings have not improved. Regarding `DocumentResultsPanel`, it's a wrapper around `DocumentSidePanel`. Its code was copied and slightly adapted from `ViewMetadataPanel`, which is also a wrapper around `DocumentSidePanel`. `ViewMetadataPanel` is also not tested.

**Comment by RafaPolit** [comment]
@txau would you be available to QA this with one of us or even Natalie (since this involves AI integration)

**Pull request merged**
