### PR TITLE
Remove private entities from inherited properties when the user is not logged in

### LINKED ISSUE #2324: Relationship field shows unpublished entities.
The relationship field shows relationships with unpublished entities, and since it renders a link to those entities you can see all the info.

Inheriting information is based on this field, so anything related to inheriting would have this problem too.

related #2313

### PR DESCRIPTION
**Pull request by habbes**
fixes #2324  #2313 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by habbes** [comment]
The updates excludes private entities from being included in inherited metadata when search for entities with geolocation (for the map view) if the user is not logged in. It also removed private relationships when fetching an entity for the entity viewer.

**Comment by habbes** [comment]
There's one outstanding issue:
The document count on the map view still counts entities with inherited geo fields from private entities, even if the private entities are not included in the payload. I think this happens because the search made elastic search returned all entities with inherited geo fields. I'm not sure how to solve this without having to resort to checking all the search results and ensuring that non of their geo fields are empty before returning the response to the client.

Screenshot 2019-07-24 at 16 36 48

**Comment by habbes** [comment]
I fixed the issue with the document count in the following way:
- I do some post-processing of the geolocation search results before sending them from the server. This post-processing removes all the entities which do not have a geolocations (includes those which have empty inherited geolocations)
- I manually set the `totalRows` of the results to match the length of `rows` array. This is because the geolocation search is designed to return all the rows and not just a subset, so it's expected that `totalRows` will be equal to the size of the `rows` array.

I had discussed this approach with @joan and we did not find a better way to solve this. This is because the elastic search query cannot filter out inherited properties based on whether the target entities are private or public, these entities are only fetched after the elastic search query is complete.

**Comment by daneryl** [comment]
@habbes can not test it, blank state + creating and publishing a single document results in an error.

`TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at entityHasGeolocation (/Users/daneryl/workspace/uwazi/app/api/search/search.js:329:12)
    at results.rows.forEach._row (/Users/daneryl/workspace/uwazi/app/api/search/search.js:361:9)
    at Array.forEach (<anonymous>)
    at processGeolocationResults (/Users/daneryl/workspace/uwazi/app/api/search/search.js:344:16)
    at Object.searchGeolocations (/Users/daneryl/workspace/uwazi/app/api/search/search.js:379:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by habbes** [comment]
@daneryl could you explain more about the document you created? I tried to blank-state and created then published a document but did not see any errors. Looking at the error message, it seems likely the it encountered an entity that does not have `metadata`. But I don't know how that could be the case if you started from a blank state. If the issue is a potential missing `metadata` field, then I can fix that but I can't tell for sure yet cause I've not managed to reproduce it.

**Comment by daneryl** [comment]
@habbes yes sorry, the error occurs after publishing the document and going to the library.

the Document is a default one only with title.

**Comment by habbes** [comment]
@daneryl I have been able to reproduce it, and it does indeed seem that the entity with the default Document template is created without `metadata` field

Screenshot 2019-07-26 at 17 56 37

**Comment by daneryl** [comment]
@habbes that means any entity can be created without metadata so we probably have those already on live instances, check for the existence of the property for now.

**Comment by habbes** [comment]
I was wondering why this entity was part of the geolocation search results for elastic search. I've found out why. The geolocation search finds all geolocation fields by scanning all templates properties, and then it filters the elastic query to include only entities with those fields. But since the Uwazi is a blank-state, it has not templates with geolocation fields, so it has no fields to filter out. This means that it returns all entities, including those without metadata.

**Comment by daneryl** [comment]
@habbes ok that sounds terrible :( can we fix quick ? returning an empty array if the case is we do not have templates with geolocation ?

**Comment by habbes** [comment]
@joan I guess that's a better fix. I fixed by removing entities that don't have metadata since I was already removing entities that don't have geolocations (during post-processing).

But I do have some recurring failed e2e tests, so those are probably not flaky tests. I'm going to look into them as well.

**Comment by habbes** [comment]
@daneryl the tests passed (I didn't change anything).

**Pull request merged**
