### PR TITLE
added inertia on mobile for browsers that support it 

### LINKED ISSUE #2430: Allow for momentum scrolling on mobile devices

### PR DESCRIPTION
**Pull request by daneryl**
fixes #2430 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by habbes** [comment]
@daneryl I tested Uwazi on Chrome for Android without without this PR and I could not reproduce the issue. The scrolling worked smoothly, including inertia/momentum scrolling.

**Comment by RafaPolit** [comment]
- [ ] @habbes Checked on Android
- [ ] @elric-wamugu Checked on Android
- [ ] @RafaPolit Checked on iOs
- [ ] @konzz Checked on iOs

**Comment by RafaPolit** [comment]
The flow part works as I would expect.  There's still a lot of mobile issues, but it's not part of this PR.  LGTM.

**Comment by elric-wamugu** [comment]
Tested on Android with the Firefox browser. The scrolling worked well.

**Pull request merged**
