### PR TITLE
Hide "sort by relevance" when not in full text search

### LINKED ISSUE #1365: Sort by relevance when no full txt search
Apparently sorting by relevance when no full text search has been queried is confusing. Maybe this property should not appear unless you've launched a full text search?

### PR DESCRIPTION
**Pull request by habbes**
fixes #1365 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by habbes** [comment]
- I've hidden "Search relevance" sort option when no full text search has been ran.
- The option is available in full text search mode. 
- If "Search relevance" was the active option in full text search, and the user removes the search keyword (i.e. leaves full text search), sorting defaults to "Creation date (recently)" automatically
- There was bug in full text search, when you tried to change the sorting from "relevance" to something else, it went back to "relevance" on its own. I've fixed this bug. Now you can select another sorting property in full text search. "Relevance" is still automatically activated when you run a search.

**Comment by daneryl** [comment]
@habbes working good, pls can you fix the codeclimate issue and rebase ? will merge

**Comment by habbes** [comment]
@daneryl fixed the codeclimate issue

**Comment by daneryl** [comment]
@habbes LGTM, rebase

**Comment by habbes** [comment]
@daneryl rebased

**Pull request merged**
