### PR TITLE
1146 downloads metadata

### PR DESCRIPTION
**Pull request by RafaPolit**
Fixes issue #1146

PR check list:

- [x] Client test
- [x] Server test
- [x] End-to-end test
- [x] Pass code linter to client and server
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA check list:

- [ ] Smoke test the functionality described in the issue
- [ ] Smoke test potential collaterals
- [ ] UI responsiveness
- [ ] Tested in a browser other than chrome
- [ ] Code review ?

NOTE: Make sure the build passes.

### CODE REVIEW

**Comment by daneryl** [comment]
@RafaPolit on library or uploads when adding an attachment the downloads list does not get updated.

issue

**Comment by RafaPolit** [comment]
@daneryl  I think we shouldn't allow to add a file from the library?

**Comment by RafaPolit** [comment]
The blank state is also missing.

**Comment by RafaPolit** [comment]
Fixed the issues with Library and Uploads.
Also, added the possibility to edit, delete and add attachments directly from the Library and Uploads, no need to go into the document or entity any more.
Blank state is now working as expected.

From my end, this is ready to merge.  Pelase QA this again.

**Pull request merged**
