### PR TITLE
3944 - Improve CSS for printing

### LINKED ISSUE #3944: Improve CSS for printing (5 pts)
On pages and entity metadata, the result of control+P could be improved in our default CSSs.

### PR DESCRIPTION
**Pull request by Zasa-san**
fixes #3944

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by grafitto** [comment]
Hi @Zasa-san this is what I get when trying to print an entity that has pdf
image
I think I should only be able to print the document. Or maybe have the entity details on the first page without the document. @konzz @RafaPolit

**Comment by Zasa-san** [comment]
> Hi @Zasa-san this is what I get when trying to print an entity that has pdf 

I don't think that printing the PDF view was needed. Just the entity view, custom page and custom entity view.

**Comment by grafitto** [comment]
Also were we allowing users print the connections page?

**Comment by Zasa-san** [comment]
> Hi @Zasa-san this is what I get when trying to print an entity that has pdf 
> Also were we allowing users print the connections page?

I think the only views to print are entity view, custom entity page, and custom pages.

**Comment by grafitto** [comment]
When viewing a list in custom entity page, this is what is seen
image
but when printing I get this
image

**Comment by grafitto** [comment]
LGTM

**Pull request merged**
