### PR TITLE
Handle mongoose validation errors

### LINKED ISSUE #2531: Avoid logging as unhandled Error, Entities title required validation.

### PR DESCRIPTION
**Pull request by habbes**
fixes #2531 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by daneryl** [comment]
@habbes when an error occurs, the error handler is throwing an error also and terminating node process, this is also happening on dev, not something added here but it is a good place to solve it if you have time take a look on that pls.

**Comment by habbes** [comment]
@daneryl could you provide an example of an error that takes down the node and how to reproduce it?

**Comment by daneryl** [comment]
@habbes you can replicate with a simple csv like this, an entity with blank title

```
Title,
title 1,
,
title 2,

**Comment by habbes** [comment]
@daneryl  I found that the error was caused by a bug in the `CSVLoader` which cause the module to throw `undefined` as the error. So the error handler ended up being called with an undefined value, and trying to access its properties eventually caused errors inside the error handled (e.g. trying to access `error.json` when `error` is `undefined`).

I have already fixed the bug in the `CSVLoader` that cause the error.

I could prevent similar errors from blowing up in the error handler by setting `error` to some default `Error` object when it comes in as undefined, but I wonder whether this could lead into critical bugs remaining hidden. What do you think?

**Comment by habbes** [comment]
@daneryl also, is there any other place where you found such an error that causes the process to terminate?

**Comment by habbes** [comment]
@daneryl when an undefined error is caught, the error handler generates a new Error with message `undefined error occurred`, since this error will receive code 500, it will be logged and the stack trace will allow us to investigate the source of the bug.

**Pull request merged**
