### PR TITLE
Setup prettier enforcement on @format pragma, improve typescript eslint

### PR DESCRIPTION
**Pull request by bdittes**
PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by daneryl** [comment]
@bdittes after using prettier on a file im getting a lot of indentation errors from eslint, if we are going to use prettier from now on should we deactivate any related code style/formatting rule from eslint ? this is great btw !

**Comment by bdittes** [comment]
I refined eslint to work better with prettier indentation - do you have an example of a file that causes trouble?

**Comment by bdittes** [comment]
I think the test is flaky (I didn't change any code...) and I have no way of even seeing the code climate issues - is there a way to run code climate locally?

**Comment by daneryl** [comment]
> I refined eslint to work better with prettier indentation - do you have an example of a file that causes trouble?

indentation is solved, there is still eslint configs that conflict with prettier, but as we talked we can refine eslint rules or deactivate if needed as we go.

> I think the test is flaky (I didn't change any code...) and I have no way of even seeing the code climate issues - is there a way to run code climate locally?

you can run codeclimate locally https://github.com/codeclimate/codeclimate, on the eslint config for eslint the typescript plugin is not listed but there is a [PR](https://github.com/codeclimate/codeclimate-eslint/pull/443) adding this some months ago, im installing it right now to test also.

**Comment by daneryl** [comment]
@bdittes aparently all the issues are indentation issues because the eslint changes, i think we do not care about indentation anymore if we using prettier, i would just deactivate eslint indentation checks, we are going to execute prettier on any file we touch anyways.

**Comment by bdittes** [comment]
Done

**Pull request merged**
