### PR TITLE
3252 card and row namespacing

### LINKED ISSUE #3252: Namespace cards and rows according to template to provide fine-tuning via CSS
Cards and Rows could be namespaced according to:
- template name
- property name
- etc?

This would allow custom CSSs to do tricks like:
- Paint a Row or a Card with different background depending on their template
- Hide a particular field (Title, for instance!) only on certain types of cards
- Custom style one property based on template + name and not forced to all types of the same source

### PR DESCRIPTION
**Pull request by RafaPolit**
fixes #3252

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by txau** [comment]
LGTM

**Comment by RafaPolit** [comment]
Some failing e2e tests.  Will check further, changing it to draft for now.

**Comment by RafaPolit** [comment]
Corrected the error.  Ready for QA.

**Comment by txau** [comment]
@RafaPolit for cards we are typing the template id, the field types and the field names. For table we are typing only the template id but not the field types and names? Is this intentional?

**Comment by RafaPolit** [comment]
Yes, it reflects the notion that, probably, you want to access the table view up till the level of the 'row'.  It could be expanded to the level of the cell right now, or further down the road.  I saw less usefulness in reaching the level of cell.  I can see a lot less cases for that.  If you think it's useful, we can go for it now, or leave it for another issue.

**Comment by txau** [comment]
@RafaPolit in that case I guess you added the template class to the TD and not to the TR so according to your explanation it is wrongly placed?

image

**Comment by RafaPolit** [comment]
The row is not aware of the data, so the class is the same for all TDs so you can intervene the "row" level, but at the TD level.

**Comment by RafaPolit** [comment]
> The row is not aware of the data, so the class is the same for all TDs so you can intervene the "row" level, but at the TD level.

Actually, this is not true.  I'll fix this.

**Pull request merged**
